# Generated by Django 4.2.18 on 2025-01-31 12:37

from django.db import migrations, models
import master.models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to=master.models.webpConverter),
        ),
    ]
